artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL : https://github.com/Vengatesan-K/Datasets-ML/raw/main/Lion_cheetah.zip
  local_data_file: artifacts/data_ingestion/Lion_cheetah.zip
  unzip_dir: artifacts/data_ingestion